<?php
namespace PepSelect\COAArchive;

if ( ! defined( 'ABSPATH' ) ) { exit; }

/** Keeps SEO-plugin sitemaps aligned with the COA archive's real public routes. */
final class SEO_Sitemaps {
	/** @var Frontend_Visibility */
	private $visibility;

	/** @var COA_Test_Repository */
	private $tests;

	/** @var Frontend_View_Model */
	private $view_model;

	public function __construct( Frontend_Visibility $visibility, COA_Test_Repository $tests, Frontend_View_Model $view_model ) {
		$this->visibility = $visibility;
		$this->tests      = $tests;
		$this->view_model = $view_model;
	}

	/** Registers only additive Yoast sitemap integrations. */
	public function register_hooks() {
		add_filter( 'wpseo_exclude_from_sitemap_by_post_ids', array( $this, 'exclude_unroutable_posts' ) );
		add_filter( 'wpseo_xml_sitemap_post_url', array( $this, 'filter_post_url' ), 10, 2 );
		add_filter( 'wpseo_sitemap_post_type_first_links', array( $this, 'add_archive_url' ), 10, 2 );
	}

	/**
	 * Excludes COA records whose plugin-owned public route would return 404.
	 *
	 * Yoast otherwise indexes the raw custom-post-type permalinks. Those URLs are
	 * intentionally blocked by Frontend_Router because they bypass compound and
	 * report visibility. Existing exclusions from other integrations are kept.
	 *
	 * @param int[] $excluded Existing excluded post IDs.
	 * @return int[]
	 */
	public function exclude_unroutable_posts( $excluded ) {
		$excluded = is_array( $excluded ) ? array_map( 'absint', $excluded ) : array();
		$ids      = get_posts(
			array(
				'post_type'      => array( Post_Types::COMPOUND, Post_Types::COA_TEST ),
				'post_status'    => 'publish',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'no_found_rows'  => true,
				'suppress_filters' => false,
			)
		);

		foreach ( $ids as $post_id ) {
			if ( '' === $this->public_url( $post_id ) ) {
				$excluded[] = absint( $post_id );
			}
		}

		return array_values( array_unique( array_filter( $excluded ) ) );
	}

	/**
	 * Replaces an internal CPT permalink with the canonical public archive URL.
	 *
	 * @param string   $url  URL generated by Yoast.
	 * @param \WP_Post $post Sitemap post.
	 * @return string
	 */
	public function filter_post_url( $url, $post ) {
		if ( ! $post instanceof \WP_Post || ! in_array( $post->post_type, array( Post_Types::COMPOUND, Post_Types::COA_TEST ), true ) ) {
			return $url;
		}

		$public_url = $this->public_url( $post );
		return '' !== $public_url ? $public_url : $url;
	}

	/**
	 * Adds the plugin-owned archive route to the first compound sitemap page.
	 *
	 * @param array[] $links     Existing first-page sitemap links.
	 * @param string  $post_type Sitemap post type.
	 * @return array[]
	 */
	public function add_archive_url( $links, $post_type ) {
		if ( Post_Types::COMPOUND !== $post_type ) {
			return $links;
		}

		$links   = is_array( $links ) ? $links : array();
		$archive = $this->view_model->archive_url();
		foreach ( $links as $link ) {
			if ( isset( $link['loc'] ) && untrailingslashit( $link['loc'] ) === untrailingslashit( $archive ) ) {
				return $links;
			}
		}

		array_unshift(
			$links,
			array(
				'loc' => $archive,
				'mod' => gmdate( 'c', $this->archive_modified_time() ),
			)
		);

		return $links;
	}

	/** Returns a public URL only when the exact frontend route resolves. */
	public function public_url( $post ) {
		$post = get_post( $post );
		if ( ! $post || 'publish' !== $post->post_status ) {
			return '';
		}

		if ( Post_Types::COMPOUND === $post->post_type ) {
			if ( ! $this->visibility->is_compound_public( $post ) || ! $this->tests->all_for_compound( $post->ID ) ) {
				return '';
			}
			return $this->view_model->compound_url( $post );
		}

		if ( Post_Types::COA_TEST !== $post->post_type || ! $this->visibility->is_test_public( $post ) ) {
			return '';
		}

		$compound_id = absint( get_post_meta( $post->ID, 'compound_id', true ) );
		$compound    = get_post( $compound_id );
		if ( ! $compound || ! $this->visibility->is_compound_public( $compound ) ) {
			return '';
		}

		$batch_slug = $this->view_model->batch_slug( $post );
		$resolved   = $this->tests->find_public_by_batch_slug( $compound_id, $batch_slug );
		if ( ! $resolved || absint( $resolved->ID ) !== absint( $post->ID ) ) {
			return '';
		}

		return $this->view_model->test_url( $compound, $post );
	}

	/** Returns the latest public COA modification time for archive lastmod. */
	private function archive_modified_time() {
		$latest = get_posts(
			array(
				'post_type'      => array( Post_Types::COMPOUND, Post_Types::COA_TEST ),
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				'orderby'        => 'modified',
				'order'          => 'DESC',
				'no_found_rows'  => true,
			)
		);
		if ( ! $latest ) {
			return time();
		}

		$modified = get_post_modified_time( 'U', true, $latest[0] );
		return $modified ? absint( $modified ) : time();
	}
}
