<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<section class="ps-coa-report-panel ps-coa-laboratory-panel" aria-labelledby="ps-laboratory-report">
	<div class="ps-coa-laboratory-panel__copy"><p class="ps-coa-eyebrow"><?php esc_html_e( 'Source documentation', 'pepselect-coa-archive' ); ?></p><h2 id="ps-laboratory-report"><?php esc_html_e( 'Laboratory Report', 'pepselect-coa-archive' ); ?></h2><p><?php esc_html_e( 'The original laboratory document is provided without alteration for independent review. Pep Select does not perform this analysis in-house.', 'pepselect-coa-archive' ); ?></p><dl>
		<?php if ( $test['laboratory'] ) : ?><div><dt><?php esc_html_e( 'Laboratory', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['laboratory'] ); ?></dd></div><?php endif; ?>
		<?php if ( $test['coa_number'] ) : ?><div><dt><?php esc_html_e( 'COA reference', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['coa_number'] ); ?></dd></div><?php endif; ?>
		<?php if ( $test['test_date_label'] ) : ?><div><dt><?php esc_html_e( 'Analysis date', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['test_date_label'] ); ?></dd></div><?php endif; ?>
		<?php if ( $test['certificate_version'] ) : ?><div><dt><?php esc_html_e( 'Certificate version', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['certificate_version'] ); ?></dd></div><?php endif; ?>
	</dl></div>
	<div class="ps-coa-laboratory-panel__actions"><div class="ps-coa-lab-identity"><span class="ps-coa-lab-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M9 3h6m-1 0v6l5 9a2 2 0 0 1-1.7 3H6.7A2 2 0 0 1 5 18l5-9V3m-3 12h10"/><path d="M8 18c2-2 3 1 5-1s3 1 4 0"/></svg></span><div><strong><?php echo esc_html( $test['laboratory'] ?: __( 'Independent laboratory', 'pepselect-coa-archive' ) ); ?></strong><span><?php esc_html_e( 'Independent Testing Laboratory', 'pepselect-coa-archive' ); ?></span><?php if ( $test['lab_report_host'] ) : ?><small><?php echo esc_html( $test['lab_report_host'] ); ?></small><?php endif; ?></div></div><div class="ps-coa-actions">
		<?php if ( $test['lab_report_url'] ) : ?><a class="ps-coa-button ps-coa-document-button" href="<?php echo esc_url( $test['lab_report_url'] ); ?>" target="_blank" rel="noopener noreferrer"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M14 4h6v6m0-6-9 9M19 13v7H4V5h7"/></svg><?php esc_html_e( 'View Verified Lab Report', 'pepselect-coa-archive' ); ?> <span class="screen-reader-text"><?php esc_html_e( '(opens in a new tab)', 'pepselect-coa-archive' ); ?></span></a><?php endif; ?>
		<?php if ( $test['pdf_url'] ) : ?><a class="ps-coa-button ps-coa-document-button ps-coa-document-button--light" href="<?php echo esc_url( $test['pdf_url'] ); ?>" target="_blank" rel="noopener noreferrer"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 3v12m-4-4 4 4 4-4M5 19h14"/></svg><?php esc_html_e( 'Download Original PDF', 'pepselect-coa-archive' ); ?> <span class="screen-reader-text"><?php esc_html_e( '(opens in a new tab)', 'pepselect-coa-archive' ); ?></span></a><?php endif; ?>
	</div></div>
</section>
