<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<article class="ps-coa-card ps-coa-latest-card">
	<header class="ps-coa-report-card__header"><div><p class="ps-coa-eyebrow"><?php esc_html_e( 'Latest Report', 'pepselect-coa-archive' ); ?></p><h3><?php echo esc_html( sprintf( __( 'Batch %s', 'pepselect-coa-archive' ), $report['batch_number'] ) ); ?></h3></div><dl><div><dt><?php esc_html_e( 'Test date', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $report['test_date_label'] ?: __( 'Not available', 'pepselect-coa-archive' ) ); ?></dd></div><div><dt><?php esc_html_e( 'Laboratory', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $report['laboratory'] ?: __( 'Not available', 'pepselect-coa-archive' ) ); ?></dd></div></dl></header>
	<div class="ps-coa-summary-metrics ps-coa-summary-metrics--latest">
		<div><span><?php esc_html_e( 'Purity', 'pepselect-coa-archive' ); ?></span><strong><?php echo '' !== $report['purity_percentage'] ? esc_html( $report['purity_percentage'] . '%' ) : esc_html__( 'Not reported', 'pepselect-coa-archive' ); ?></strong><?php if ( $report['purity_status']['value'] ) : ?><?php $status = $report['purity_status']; include pepselect_coa_template_path( 'partials/status-indicator.php' ); ?><?php endif; ?></div>
		<div><span><?php esc_html_e( 'Net content', 'pepselect-coa-archive' ); ?></span><strong><?php echo esc_html( trim( $report['average_net_content'] . ' ' . $report['content_unit'] ) ?: __( 'Not reported', 'pepselect-coa-archive' ) ); ?></strong></div>
		<?php if ( $report['claimed_content'] ) : ?><div><span><?php esc_html_e( 'Labeled content', 'pepselect-coa-archive' ); ?></span><strong><?php echo esc_html( trim( $report['claimed_content'] . ' ' . $report['content_unit'] ) ); ?></strong></div><?php endif; ?>
		<?php if ( $report['vials_tested'] ) : ?><div><span><?php esc_html_e( 'Vials tested', 'pepselect-coa-archive' ); ?></span><strong><?php echo esc_html( $report['vials_tested'] ); ?></strong></div><?php endif; ?>
	</div>
	<div class="ps-coa-status-row"><?php foreach ( array( 'identity_status' => __( 'Identity', 'pepselect-coa-archive' ), 'heavy_metals_status' => __( 'Heavy metals', 'pepselect-coa-archive' ), 'sterility_status' => __( 'Sterility', 'pepselect-coa-archive' ), 'endotoxin_status' => __( 'Endotoxin', 'pepselect-coa-archive' ) ) as $key => $label ) : ?><div><span><?php echo esc_html( $label ); ?></span><?php $status = $report[ $key ]; include pepselect_coa_template_path( 'partials/status-indicator.php' ); ?></div><?php endforeach; ?></div>
	<footer><a class="ps-coa-button ps-coa-button--primary" href="<?php echo esc_url( $report['detail_url'] ); ?>"><?php esc_html_e( 'View Full Report', 'pepselect-coa-archive' ); ?></a></footer>
</article>
