<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<article class="ps-coa-card ps-coa-previous-card ps-coa-previous-card--<?php echo esc_attr( $report['public_status_tone'] ); ?>">
	<?php if ( $report['vial_image_url'] ) : ?><img class="ps-coa-previous-card__image" src="<?php echo esc_url( $report['vial_image_url'] ); ?>"<?php if ( $report['vial_image_srcset'] ) : ?> srcset="<?php echo esc_attr( $report['vial_image_srcset'] ); ?>"<?php endif; ?><?php if ( $report['vial_image_sizes'] ) : ?> sizes="<?php echo esc_attr( $report['vial_image_sizes'] ); ?>"<?php endif; ?> alt="<?php echo esc_attr( $report['vial_image_alt'] ); ?>" loading="lazy"><?php endif; ?>
	<header><h3><?php echo esc_html( sprintf( __( 'Batch %s', 'pepselect-coa-archive' ), $report['batch_number'] ) ); ?></h3><p><?php echo esc_html( $report['test_date_label'] ?: __( 'Date not available', 'pepselect-coa-archive' ) ); ?> <span aria-hidden="true">&middot;</span> <?php echo esc_html( $report['laboratory'] ?: __( 'Laboratory not available', 'pepselect-coa-archive' ) ); ?></p></header>
	<div class="ps-coa-assurance ps-coa-assurance--compact ps-coa-assurance--<?php echo esc_attr( $report['public_status_tone'] ); ?>"><span aria-hidden="true"></span><div><strong><?php echo esc_html( $report['public_status_label'] ); ?></strong><?php if ( $report['public_status_copy'] ) : ?><small><?php echo esc_html( $report['public_status_copy'] ); ?></small><?php endif; ?></div></div>
	<?php if ( 'failed' === $report['coa_status'] && $report['release_decision_note'] ) : ?><p class="ps-coa-release-decision"><?php echo esc_html( $report['release_decision_note'] ); ?></p><?php endif; ?>
	<dl class="ps-coa-previous-card__metrics"><div><dt><?php esc_html_e( 'Purity', 'pepselect-coa-archive' ); ?></dt><dd><?php echo '' !== $report['purity_percentage_display'] ? esc_html( $report['purity_percentage_display'] . '%' ) : esc_html__( 'Not reported', 'pepselect-coa-archive' ); ?></dd></div><div><dt><?php esc_html_e( 'Net content', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( trim( $report['average_net_content_display'] . ' ' . $report['content_unit'] ) ?: __( 'Not reported', 'pepselect-coa-archive' ) ); ?></dd></div></dl>
	<div class="ps-coa-status-list"><?php foreach ( array( 'identity_status' => __( 'Identity', 'pepselect-coa-archive' ), 'heavy_metals_status' => __( 'Heavy metals', 'pepselect-coa-archive' ), 'sterility_status' => __( 'Sterility', 'pepselect-coa-archive' ), 'endotoxin_status' => __( 'Endotoxin', 'pepselect-coa-archive' ) ) as $key => $label ) : ?><div><span><?php echo esc_html( $label ); ?></span><?php $status = $report[ $key ]; include pepselect_coa_template_path( 'partials/status-indicator.php' ); ?></div><?php endforeach; ?></div>
	<footer><a class="ps-coa-text-link" href="<?php echo esc_url( $report['detail_url'] ); ?>"><?php echo esc_html( \PepSelect\COAArchive\Design_Settings::copy( 'failed' === $report['coa_status'] ? 'view_failed_report' : 'view_report' ) ); ?> <span aria-hidden="true">&rarr;</span></a></footer>
</article>
