<?php
/** COA-4E.2 beta.10 exact Full-QC bar, Fentanyl Screen, and regression coverage. */
class PepSelect_COA_Archive_COA_4E_Visual_Revision_Test extends WP_UnitTestCase {
	private $view;
	private $validator;

	public function set_up() {
		parent::set_up();
		do_action( 'init' );
		PepSelect\COAArchive\Capabilities::grant_to_administrators();
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'administrator' ) ) );
		$this->view = new PepSelect\COAArchive\Frontend_View_Model();
		$this->validator = new PepSelect\COAArchive\COA_Test_Validation();
	}

	public function tear_down() { unset( $_POST['acf'], $_POST['post_ID'], $_POST['post_status'] ); parent::tear_down(); }

	public function test_01_fentanyl_status_field_is_registered() { $field = $this->field( 'fentanyl_status' ); $this->assertSame( 'field_ps_coa_test_fentanyl_status', $field['key'] ); $this->assertSame( 'select', $field['type'] ); }
	public function test_02_fentanyl_result_field_is_registered() { $field = $this->field( 'fentanyl_result' ); $this->assertSame( 'field_ps_coa_test_fentanyl_result', $field['key'] ); $this->assertSame( 'text', $field['type'] ); }
	public function test_03_fentanyl_method_field_is_registered() { $field = $this->field( 'fentanyl_method' ); $this->assertSame( 'field_ps_coa_test_fentanyl_method', $field['key'] ); $this->assertSame( 'Immunoassay', $field['default_value'] ); $this->assertSame( 1, $field['readonly'] ); }
	public function test_04_fentanyl_specification_field_is_registered() { $field = $this->field( 'fentanyl_specification' ); $this->assertSame( 'field_ps_coa_test_fentanyl_specification', $field['key'] ); $this->assertSame( 'Immunoassay, 50 ng/mL cutoff', $field['default_value'] ); $this->assertSame( 1, $field['readonly'] ); }
	public function test_05_fentanyl_notes_field_is_registered() { $field = $this->field( 'fentanyl_notes' ); $this->assertSame( 'field_ps_coa_test_fentanyl_notes', $field['key'] ); $this->assertSame( 0, $field['required'] ); }
	public function test_06_fentanyl_status_has_only_requested_choices() { $field = $this->field( 'fentanyl_status' ); $this->assertSame( 'not-tested', $field['default_value'] ); $this->assertSame( array( 'pass', 'fail', 'not-tested' ), array_keys( $field['choices'] ) ); $this->assertNotSame( 'pass', $field['default_value'] ); }
	public function test_07_fentanyl_fields_are_unavailable_during_vendor_vetting() { $this->assertFentanylAvailability( 'vendor-vetting', false, false ); }
	public function test_08_fentanyl_fields_are_unavailable_while_waiting_on_vendor() { $this->assertFentanylAvailability( 'waiting-on-vendor', false, false ); }
	public function test_09_fentanyl_fields_are_unavailable_before_lab_submission() { $this->assertFentanylAvailability( 'submitted-to-lab', false, false ); }
	public function test_10_fentanyl_fields_are_available_during_partial_result_entry() { $this->assertFentanylAvailability( 'in-testing', false, false ); $this->assertFentanylAvailability( 'in-testing', true, true ); }
	public function test_11_fentanyl_fields_are_available_at_complete() { $this->assertFentanylAvailability( 'complete', false, true ); }
	public function test_12_approved_complete_ils_requires_passing_fentanyl_result() { $_POST['acf'] = array( 'field_ps_coa_test_workflow_stage' => 'complete', 'field_ps_coa_test_testing_lab' => 'ils-labs', 'field_ps_coa_test_fentanyl_status' => 'not-tested' ); $this->assertSame( 'Completed approved ILS reports require a passing Fentanyl Screen at the 50 ng/mL cutoff.', $this->validator->validate_approval( true, 'approved', array(), '' ) ); }
	public function test_13_failed_complete_may_store_failed_fentanyl_result() { $_POST['acf'] = array( 'field_ps_coa_test_workflow_stage' => 'complete', 'field_ps_coa_test_testing_lab' => 'ils-labs', 'field_ps_coa_test_fentanyl_status' => 'fail', 'field_ps_coa_test_fentanyl_result' => 'Detected', 'field_ps_coa_test_release_decision_note' => 'Not released.' ); $this->assertTrue( $this->validator->validate_approval( true, 'failed', array(), '' ) ); }
	public function test_14_blank_data_keeps_neutral_fentanyl_position() { $row = $this->strip_row( $this->full_fixture( '', '', '', '' ), 'fentanyl' ); $this->assertSame( '--', $row['detail'] ); $this->assertFalse( $row['status']['success'] ); }
	public function test_15_unsupported_fentanyl_status_keeps_neutral_position() { $row = $this->strip_row( $this->full_fixture( 'pending', 'Not detected' ), 'fentanyl' ); $this->assertSame( '--', $row['detail'] ); $this->assertFalse( $row['status']['success'] ); }
	public function test_16_not_tested_fentanyl_is_not_successful() { $row = $this->strip_row( $this->full_fixture( 'not-tested', 'Not tested' ), 'fentanyl' ); $this->assertSame( 'Fentanyl Screen', $row['short_label'] ); $this->assertFalse( $row['status']['success'] ); }
	public function test_17_failed_fentanyl_is_not_successful() { $row = $this->strip_row( $this->full_fixture( 'fail', 'Detected', 'Immunoassay', 'Immunoassay, 50 ng/mL cutoff', 'failed' ), 'fentanyl' ); $this->assertSame( 'Fentanyl Screen', $row['short_label'] ); $this->assertFalse( $row['status']['success'] ); }
	public function test_18_successful_result_renders_fentanyl_screen() { $row = $this->strip_row( $this->full_fixture( 'pass', 'Not detected' ), 'fentanyl' ); $this->assertSame( 'Fentanyl Screen', $row['short_label'] ); $this->assertTrue( $row['status']['success'] ); }
	public function test_19_successful_result_appears_in_full_qc_strip() { $row = $this->strip_row( $this->full_fixture( 'pass', 'Not detected' ), 'fentanyl' ); $this->assertSame( 'Fentanyl Screen', $row['short_label'] ); $this->assertSame( 'Not detected', $row['detail'] ); }
	public function test_20_fentanyl_screen_appears_in_detailed_table() { $model = $this->report( $this->full_fixture( 'pass', 'Not detected' ) ); $row = array_values( array_filter( $model['result_rows'], static function ( $item ) { return 'fentanyl' === $item['key']; } ) )[0]; $this->assertSame( 'Fentanyl Screen', $row['label'] ); $this->assertSame( 'Immunoassay', $row['method'] ); $this->assertSame( '50 ng/mL cutoff', $row['specification'] ); $this->assertSame( 'Not detected', $row['result'] ); $this->assertSame( 'Pass', $row['status']['label'] ); }
	public function test_21_existing_csv_without_fentanyl_columns_remains_supported() { $map = $this->importer_map(); $this->assertSame( 'field_ps_coa_test_batch_number', $map['batch_number'] ); $this->assertSame( 'field_ps_coa_test_purity_percentage', $map['purity_percentage'] ); }
	public function test_22_all_fentanyl_csv_headers_map_correctly() { $map = $this->importer_map(); foreach ( $this->fentanyl_fields() as $name ) { $this->assertSame( 'field_ps_coa_test_' . $name, $map[ $name ] ); } }
	public function test_23_invalid_fentanyl_status_is_rejected() { $_POST['acf'] = array( 'field_ps_coa_test_workflow_stage' => 'complete' ); $this->assertNotTrue( $this->validator->validate( true, 'not-applicable', array( 'name' => 'fentanyl_status' ), '' ) ); $this->assertStringContainsString( "const fentanylStatuses = new Set( [ 'pass', 'fail', 'not-tested' ] )", $this->importer_js() ); }
	public function test_24_blank_status_is_not_inferred_as_pass() { $this->assertSame( '', PepSelect\COAArchive\COA_Test_Validation::sanitize( '', 'fentanyl_status' ) ); $this->assertStringContainsString( "if ( '' === raw ) { return { valid: true, value: '' }; }", $this->importer_js() ); }
	public function test_25_csv_javascript_populates_fentanyl_fields() { $source = $this->importer_js(); foreach ( $this->fentanyl_fields() as $name ) { $this->assertStringContainsString( $name, $source ); } $this->assertStringContainsString( 'normalizeFentanylResult', $source ); $this->assertStringContainsString( 'setFieldValue', $source ); }
	public function test_26_measured_values_contains_strip_after_metric_cards() { $source = $this->template( 'single-coa-report.php' ); $start = strpos( $source, 'ps-coa-measured-values' ); $strip = strpos( $source, 'partials/full-qc-status-strip.php', $start ); $metrics = strpos( $source, 'partials/report-summary-metrics.php', $start ); $this->assertNotFalse( $start ); $this->assertGreaterThan( $start, $metrics ); $this->assertGreaterThan( $metrics, $strip ); }
	public function test_27_full_qc_strip_uses_expected_supported_categories() { $this->assertSame( array( 'Identity', 'Purity', 'Net Content', 'Heavy Metals', 'Sterility', 'Endotoxins', 'Fentanyl Screen' ), $this->strip_labels( $this->full_fixture( 'pass', 'Not detected' ) ) ); }
	public function test_28_four_summary_cards_render() { $this->assertSame( 4, substr_count( $this->template( 'partials/report-summary-metrics.php' ), 'class="ps-coa-report-metric"' ) ); }
	public function test_29_independent_laboratory_data_table_renders() { $report = $this->template( 'single-coa-report.php' ); $table = $this->template( 'partials/full-qc-results-table.php' ); $this->assertStringContainsString( 'Independent laboratory data', $report ); foreach ( array( 'Test', 'Method', 'Specification', 'Result', 'Status' ) as $heading ) { $this->assertStringContainsString( "'" . $heading . "'", $table ); } }
	public function test_30_original_document_panel_renders() { $source = $this->template( 'partials/certificate-pages.php' ); $this->assertStringContainsString( 'ps-coa-report-panel ps-coa-certificate', $source ); $this->assertStringContainsString( 'Original document', $source ); }
	public function test_31_source_documentation_panel_renders() { $source = $this->template( 'partials/laboratory-report-panel.php' ); $this->assertStringContainsString( 'ps-coa-laboratory-panel', $source ); $this->assertStringContainsString( 'Source documentation', $source ); $this->assertStringContainsString( 'Laboratory Report', $source ); }
	public function test_32_final_lab_url_uses_exact_lab_report_url() { $ids = $this->full_fixture( 'pass', 'Not detected' ); update_post_meta( $ids['test'], 'lab_report_url', 'https://labs.example/exact-report' ); $this->assertSame( 'https://labs.example/exact-report', $this->report( $ids )['lab_report_url'] ); $this->assertStringNotContainsString( 'pending_lab_url', $this->template( 'partials/laboratory-report-panel.php' ) ); }
	public function test_33_pdf_button_uses_a_valid_attachment() { $ids = $this->full_fixture( 'pass', 'Not detected' ); $pdf = $this->attachment( 'application/pdf' ); update_post_meta( $ids['test'], 'coa_pdf_id', $pdf ); $this->assertNotSame( '', $this->report( $ids )['pdf_url'] ); update_post_meta( $ids['test'], 'coa_pdf_id', $this->attachment( 'image/jpeg' ) ); $this->assertSame( '', $this->report( $ids )['pdf_url'] ); }
	public function test_34_private_access_codes_remain_hidden() { $source = $this->public_templates(); $this->assertStringNotContainsString( 'verification_code', $source ); $this->assertStringNotContainsString( 'Access Code', $source ); }
	public function test_35_laboratory_street_address_remains_hidden() { $source = strtolower( $this->public_templates() ); $this->assertStringNotContainsString( 'street_address', $source ); $this->assertStringNotContainsString( 'laboratory address', $source ); }
	public function test_36_approved_layout_uses_success_styling() { $this->assertStringContainsString( 'ps-coa-report--mockup-layout', $this->template( 'single-coa-report.php' ) ); $this->assertStringContainsString( 'ps-coa-report-hero__outcome--success', $this->css() ); $this->assertStringContainsString( 'The QC testing passed.', $this->template( 'partials/report-hero.php' ) ); }
	public function test_37_failed_layout_does_not_use_approved_strip() { $source = $this->template( 'single-coa-report.php' ); $this->assertStringContainsString( "\$test['show_qc_strip']", $source ); $this->assertStringNotContainsString( "'failed' === \$test['coa_status'] && \$test['is_full_qc_documented']", $source ); $this->assertStringContainsString( 'ps-coa-report-hero__outcome--failed', $this->css() ); }
	public function test_38_incoming_layout_does_not_show_fake_results() { $compound = $this->compound(); $test = $this->test_post( $compound, 'pending', 'in-testing' ); $model = $this->view->report( get_post( $test ), get_post( $compound ) ); $this->assertFalse( $model['has_summary_metrics'] ); $this->assertEmpty( $model['result_rows'] ); $this->assertFalse( $model['is_full_qc_documented'] ); }
	public function test_39_mobile_result_cards_contain_all_table_information() { $template = $this->template( 'partials/full-qc-results-table.php' ); foreach ( array( 'Method', 'Specification', 'Result', 'Status' ) as $label ) { $this->assertStringContainsString( "'" . $label . "'", $template ); } $this->assertStringContainsString( '.ps-coa-report--mockup-layout .ps-coa-results-cards { display: grid', $this->css() ); }
	public function test_40_existing_lightbox_remains_functional() { $this->assertFileExists( dirname( __DIR__ ) . '/assets/js/pepselect-coa-lightbox.js' ); $this->assertStringContainsString( 'data-ps-coa-gallery', $this->template( 'partials/certificate-pages.php' ) ); $this->assertStringContainsString( 'data-ps-coa-full', $this->template( 'partials/certificate-pages.php' ) ); }
	public function test_41_existing_archive_route_remains_functional() { $this->assertStringContainsString( 'testing/?$', file_get_contents( dirname( __DIR__ ) . '/includes/class-rewrites.php' ) ); }
	public function test_42_existing_history_route_remains_functional() { $this->assertStringContainsString( 'testing/([^/]+)/?$', file_get_contents( dirname( __DIR__ ) . '/includes/class-rewrites.php' ) ); }
	public function test_43_existing_admin_workflow_remains_functional() { $source = file_get_contents( dirname( __DIR__ ) . '/includes/class-coa-test-form.php' ); $this->assertStringContainsString( 'admin_enqueue_scripts', $source ); $this->assertStringContainsString( 'partial_results_available', $source ); $this->assertStringContainsString( 'COA_Workflow::stages()', $source ); }
	public function test_44_no_woocommerce_product_page_hooks_are_added() { $source = $this->all_php(); foreach ( array( 'woocommerce_before_single_product', 'woocommerce_single_product_summary', 'woocommerce_after_single_product' ) as $hook ) { $this->assertStringNotContainsString( $hook, $source ); } }
	public function test_45_no_qr_code_functionality_is_added() { $source = strtolower( $this->all_php() . $this->public_templates() ); $this->assertStringNotContainsString( 'qrcode', $source ); $this->assertStringNotContainsString( 'qr_code', $source ); }

	private function fields() { $method = new ReflectionMethod( 'PepSelect\\COAArchive\\COA_Test_Fields', 'fields' ); $method->setAccessible( true ); return $method->invoke( new PepSelect\COAArchive\COA_Test_Fields( new PepSelect\COAArchive\Dependencies() ) ); }
	private function field( $name ) { foreach ( $this->fields() as $field ) { if ( isset( $field['name'] ) && $name === $field['name'] ) { return $field; } } $this->fail( 'Missing field: ' . $name ); }
	private function importer_map() { $method = new ReflectionMethod( 'PepSelect\\COAArchive\\COA_Test_Importer', 'field_map' ); $method->setAccessible( true ); return $method->invoke( new PepSelect\COAArchive\COA_Test_Importer() ); }
	private function fentanyl_fields() { return array( 'fentanyl_status', 'fentanyl_result', 'fentanyl_method', 'fentanyl_specification', 'fentanyl_notes' ); }
	private function assertFentanylAvailability( $stage, $partial, $expected ) { foreach ( $this->fentanyl_fields() as $name ) { $this->assertSame( $expected, PepSelect\COAArchive\COA_Test_Form::field_available( $name, $stage, $partial ), $name ); } }
	private function compound() { $id = self::factory()->post->create( array( 'post_type' => 'ps_compound', 'post_status' => 'publish', 'post_title' => 'Retatrutide' ) ); update_post_meta( $id, 'is_active', 1 ); update_post_meta( $id, 'compound_name', 'Retatrutide' ); update_post_meta( $id, 'strength_value', '30' ); update_post_meta( $id, 'strength_unit', 'mg' ); return $id; }
	private function test_post( $compound, $status, $stage ) { $id = self::factory()->post->create( array( 'post_type' => 'ps_coa_test', 'post_status' => 'publish', 'post_title' => 'Batch REV-1' ) ); foreach ( array( 'compound_id' => $compound, 'coa_status' => $status, 'workflow_stage' => $stage, 'batch_number' => 'REV-1' ) as $key => $value ) { update_post_meta( $id, $key, $value ); } return $id; }
	private function full_fixture( $fentanyl_status, $fentanyl_result, $fentanyl_method = 'Immunoassay', $fentanyl_specification = 'Immunoassay, 50 ng/mL cutoff', $outcome = 'approved' ) { $compound = $this->compound(); $test = $this->test_post( $compound, $outcome, 'complete' ); $values = array( 'testing_lab' => 'ils-labs', 'test_date' => '20260710', 'claimed_content' => '30', 'content_unit' => 'mg', 'vials_tested' => '3', 'average_net_content' => '31.01', 'minimum_net_content' => '30.82', 'maximum_net_content' => '31.22', 'purity_percentage' => '99.79', 'purity_status' => 'pass', 'purity_method' => 'HPLC', 'identity_status' => 'pass', 'identity_method' => 'LC-MS', 'heavy_metals_status' => 'pass', 'heavy_metals_summary' => 'Not detected', 'sterility_status' => 'pass', 'sterility_result' => 'No growth', 'endotoxin_status' => 'pass', 'endotoxin_result' => '< 0.05', 'endotoxin_unit' => 'EU/mL', 'fentanyl_status' => $fentanyl_status, 'fentanyl_result' => $fentanyl_result, 'fentanyl_method' => $fentanyl_method, 'fentanyl_specification' => $fentanyl_specification ); foreach ( $values as $key => $value ) { if ( '' !== $value ) { update_post_meta( $test, $key, $value ); } } return array( 'compound' => $compound, 'test' => $test ); }
	private function report( $ids ) { return $this->view->report( get_post( $ids['test'] ), get_post( $ids['compound'] ) ); }
	private function strip_labels( $ids ) { return wp_list_pluck( $this->report( $ids )['qc_strip_rows'], 'short_label' ); }
	private function strip_row( $ids, $key ) { $rows = array_values( array_filter( $this->report( $ids )['qc_strip_rows'], static function ( $row ) use ( $key ) { return $key === $row['key']; } ) ); $this->assertCount( 1, $rows ); return $rows[0]; }
	private function attachment( $mime ) { return self::factory()->post->create( array( 'post_type' => 'attachment', 'post_status' => 'inherit', 'post_mime_type' => $mime, 'guid' => 'https://example.org/media/' . wp_generate_uuid4() ) ); }
	private function template( $path ) { return file_get_contents( dirname( __DIR__ ) . '/templates/' . $path ); }
	private function css() { return file_get_contents( dirname( __DIR__ ) . '/assets/css/pepselect-coa-frontend.css' ); }
	private function importer_js() { return file_get_contents( dirname( __DIR__ ) . '/assets/js/coa-test-importer.js' ); }
	private function public_templates() { $source = ''; foreach ( glob( dirname( __DIR__ ) . '/templates/*.php' ) as $path ) { $source .= file_get_contents( $path ); } foreach ( glob( dirname( __DIR__ ) . '/templates/partials/*.php' ) as $path ) { $source .= file_get_contents( $path ); } return $source; }
	private function all_php() { $source = ''; foreach ( glob( dirname( __DIR__ ) . '/includes/*.php' ) as $path ) { $source .= file_get_contents( $path ); } return $source; }
}
