<?php
/** COA-4E exact-batch identity, report composition, and regression tests. */
class PepSelect_COA_Archive_COA_4E_Test extends WP_UnitTestCase {
	private $validator;
	private $view;

	public function set_up() {
		parent::set_up();
		do_action( 'init' );
		PepSelect\COAArchive\Capabilities::grant_to_administrators();
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'administrator' ) ) );
		$this->validator = new PepSelect\COAArchive\COA_Test_Validation();
		$this->view = new PepSelect\COAArchive\Frontend_View_Model();
	}

	public function tear_down() { unset( $_POST['acf'], $_POST['post_ID'], $_POST['post_status'] ); parent::tear_down(); }

	public function test_01_batch_vial_photo_field_is_registered() { $this->assertStringContainsString( "'batch_vial_photo', 'Batch Vial Photo', 'image'", $this->fields() ); $this->assertStringContainsString( "'key' => 'field_ps_coa_test_' . \$suffix", $this->fields() ); }
	public function test_02_batch_identity_gallery_is_registered() { $this->assertStringContainsString( "'batch_identity_photos', 'Batch Identity Photos', 'gallery'", $this->fields() ); $this->assertStringContainsString( "'key' => 'field_ps_coa_test_' . \$suffix", $this->fields() ); }
	public function test_03_valid_batch_vial_image_is_accepted() { $_POST['acf'] = $this->stage( 'in-testing' ); $this->assertTrue( $this->validate( $this->attachment( 'image/jpeg' ), 'batch_vial_photo' ) ); }
	public function test_04_non_image_batch_vial_attachment_is_rejected() { $_POST['acf'] = $this->stage( 'in-testing' ); $this->assertNotTrue( $this->validate( $this->attachment( 'application/pdf' ), 'batch_vial_photo' ) ); }
	public function test_05_batch_vial_photo_is_optional_during_vendor_vetting() { $_POST['acf'] = $this->stage( 'vendor-vetting' ); $this->assertTrue( $this->validate( '', 'batch_vial_photo' ) ); }
	public function test_06_batch_vial_photo_is_optional_while_waiting_on_vendor() { $_POST['acf'] = $this->stage( 'waiting-on-vendor' ); $this->assertTrue( $this->validate( '', 'batch_vial_photo' ) ); }
	public function test_07_batch_vial_photo_is_optional_when_submitted_to_lab() { $_POST['acf'] = $this->stage( 'submitted-to-lab' ); $this->assertTrue( $this->validate( '', 'batch_vial_photo' ) ); }
	public function test_08_batch_vial_photo_is_required_during_verification() { $_POST['acf'] = $this->stage( 'in-testing' ); $this->assertSame( 'A photo of the exact tested vial is required before Verification in Progress or Complete can be saved.', $this->validate( '', 'batch_vial_photo' ) ); }
	public function test_09_batch_vial_photo_is_required_when_complete() { $_POST['acf'] = $this->stage( 'complete' ); $this->assertSame( 'A photo of the exact tested vial is required before Verification in Progress or Complete can be saved.', $this->validate( '', 'batch_vial_photo' ) ); }
	public function test_10_legacy_complete_report_remains_public() { $compound = $this->compound(); $test = $this->test_record( $compound ); $this->assertTrue( ( new PepSelect\COAArchive\Frontend_Visibility() )->is_test_public( $test, $compound ) ); $_POST['post_ID'] = $test; $_POST['acf'] = array_merge( $this->stage( 'complete' ), array( 'field_ps_coa_test_status' => 'approved', 'field_ps_coa_test_batch_number' => 'LEGACY' ) ); $this->assertTrue( $this->validate( '', 'batch_vial_photo' ) ); $_POST['acf']['field_ps_coa_test_batch_number'] = 'CHANGED'; $this->assertNotTrue( $this->validate( '', 'batch_vial_photo' ) ); }
	public function test_11_batch_identity_gallery_order_is_preserved() { $this->assertSame( array( 9, 2, 7 ), PepSelect\COAArchive\COA_Test_Validation::sanitize_gallery( array( '9', '2', '7' ) ) ); }
	public function test_12_batch_vial_photo_is_first_public_fallback() { $ids = $this->fallback_fixture(); update_post_meta( $ids['test'], 'batch_vial_photo', $ids['batch'] ); $model = $this->summary( $ids ); $this->assertSame( $ids['batch'], $model['vial_image_id'] ); $this->assertSame( 'batch-vial-photo', $model['vial_image_source'] ); }
	public function test_13_featured_image_is_second_public_fallback() { $ids = $this->fallback_fixture(); update_post_meta( $ids['test'], '_thumbnail_id', $ids['featured'] ); $model = $this->summary( $ids ); $this->assertSame( $ids['featured'], $model['vial_image_id'] ); $this->assertSame( 'featured-image', $model['vial_image_source'] ); }
	public function test_14_compound_image_is_third_public_fallback() { $ids = $this->fallback_fixture(); update_post_meta( $ids['compound'], 'compound_image_id', $ids['compound_image'] ); $model = $this->summary( $ids ); $this->assertSame( $ids['compound_image'], $model['vial_image_id'] ); $this->assertSame( 'compound-image', $model['vial_image_source'] ); }
	public function test_15_local_placeholder_is_final_public_fallback() { $ids = $this->fallback_fixture(); $model = $this->summary( $ids ); $this->assertSame( 'local-placeholder', $model['vial_image_source'] ); $this->assertStringContainsString( 'assets/images/neutral-vial.svg', $model['vial_image_url'] ); }
	public function test_16_full_report_hero_renders_report_identity() { $hero = $this->template( 'partials/report-hero.php' ); $this->assertStringContainsString( 'ps-coa-report-hero__identity', $hero ); $this->assertStringContainsString( "compound['public_name']", $hero ); }
	public function test_17_full_report_hero_renders_tested_vial() { $hero = $this->template( 'partials/report-hero.php' ); $this->assertStringContainsString( "partials/batch-vial-image.php", $hero ); $this->assertStringContainsString( 'object-fit:contain', str_replace( ' ', '', $this->css() ) ); }
	public function test_18_approved_outcome_is_conditional() { $hero = $this->template( 'partials/report-hero.php' ); $this->assertStringContainsString( "'approved' === \$test['coa_status']", $hero ); $this->assertStringContainsString( 'Approved', $hero ); }
	public function test_19_failed_outcome_is_conditional() { $hero = $this->template( 'partials/report-hero.php' ); $this->assertStringContainsString( "'failed' === \$test['coa_status']", $hero ); $this->assertStringContainsString( 'Did Not Pass Release Review', $hero ); }
	public function test_20_access_code_is_not_rendered_publicly() { $this->assertStringNotContainsString( 'verification_code', $this->public_templates() ); $this->assertStringNotContainsString( 'Access Code', $this->public_templates() ); }
	public function test_21_generic_verification_url_is_not_rendered_publicly() { $this->assertStringNotContainsString( 'lab_verification_url', $this->public_templates() ); }
	public function test_22_laboratory_street_address_is_not_rendered_publicly() { $this->assertStringNotContainsString( 'street_address', $this->public_templates() ); $this->assertStringNotContainsString( 'laboratory_address', $this->public_templates() ); }
	public function test_23_summary_metrics_render_only_actual_values() { $template = $this->template( 'partials/report-summary-metrics.php' ); $this->assertStringContainsString( "if ( '' !== \$test['purity_percentage_display'] )", $template ); $this->assertStringNotContainsString( '99.79', $template ); }
	public function test_24_public_numbers_use_the_existing_formatter() { $source = file_get_contents( dirname( __DIR__ ) . '/includes/class-frontend-view-model.php' ); $this->assertStringContainsString( 'pepselect_coa_format_number( $purity', $source ); $this->assertStringContainsString( 'pepselect_coa_format_number( $average', $source ); }
	public function test_25_full_qc_strip_uses_status_aware_recorded_rows() { $template = $this->template( 'partials/full-qc-status-strip.php' ); $this->assertStringContainsString( "test['qc_strip_rows']", $template ); $this->assertStringContainsString( "row['status']['success']", $template ); $this->assertStringNotContainsString( "test['result_rows']", $template ); }
	public function test_26_missing_fentanyl_never_appears_as_pass() { $ids = $this->fallback_fixture(); $model = $this->view->report( get_post( $ids['test'] ), get_post( $ids['compound'] ) ); $this->assertEmpty( array_filter( $model['result_rows'], function ( $row ) { return 'fentanyl' === $row['key']; } ) ); $this->assertSame( 'Not Reported', $model['fentanyl_status']['label'] ); }
	public function test_27_saved_fentanyl_data_renders_truthfully() { $ids = $this->fallback_fixture(); update_post_meta( $ids['test'], 'fentanyl_status', 'pass' ); update_post_meta( $ids['test'], 'fentanyl_result', 'Not detected' ); update_post_meta( $ids['test'], 'fentanyl_method', 'Immunoassay' ); $model = $this->view->report( get_post( $ids['test'] ), get_post( $ids['compound'] ) ); $row = array_values( array_filter( $model['result_rows'], function ( $item ) { return 'fentanyl' === $item['key']; } ) )[0]; $this->assertSame( 'Pass', $row['status']['label'] ); $this->assertSame( 'Not detected', $row['result'] ); }
	public function test_28_full_qc_table_omits_empty_rows() { $ids = $this->fallback_fixture(); $model = $this->view->report( get_post( $ids['test'] ), get_post( $ids['compound'] ) ); $this->assertEmpty( $model['result_rows'] ); }
	public function test_29_certificate_page_order_is_preserved() { $ids = $this->fallback_fixture(); $first = $this->attachment( 'image/jpeg' ); $second = $this->attachment( 'image/png' ); update_post_meta( $ids['test'], 'coa_page_images', array( $second, $first ) ); $model = $this->view->report( get_post( $ids['test'] ), get_post( $ids['compound'] ) ); $this->assertSame( array( $second, $first ), wp_list_pluck( $model['page_images'], 'attachment_id' ) ); }
	public function test_30_batch_photos_are_separate_from_certificate_pages() { $report = $this->template( 'single-coa-report.php' ); $this->assertStringContainsString( 'partials/certificate-pages.php', $report ); $this->assertStringContainsString( 'partials/batch-identity-gallery.php', $report ); $this->assertNotSame( strpos( $report, 'certificate-pages.php' ), strpos( $report, 'batch-identity-gallery.php' ) ); }
	public function test_31_final_lab_button_uses_exact_saved_url() { $panel = $this->template( 'partials/laboratory-report-panel.php' ); $this->assertStringContainsString( "test['lab_report_url']", $panel ); $this->assertStringNotContainsString( 'verification_code', $panel ); $this->assertStringNotContainsString( 'pending_lab_url', $panel ); }
	public function test_32_pdf_button_requires_valid_pdf_url() { $panel = $this->template( 'partials/laboratory-report-panel.php' ); $this->assertStringContainsString( "if ( \$test['pdf_url'] )", $panel ); $this->assertStringContainsString( "test['pdf_url']", $panel ); }
	public function test_33_incoming_reports_do_not_show_fake_metrics() { $compound = $this->compound(); $test = self::factory()->post->create( array( 'post_type' => 'ps_coa_test', 'post_status' => 'publish' ) ); update_post_meta( $test, 'compound_id', $compound ); update_post_meta( $test, 'workflow_stage', 'in-testing' ); update_post_meta( $test, 'coa_status', 'pending' ); $model = $this->view->report( get_post( $test ), get_post( $compound ) ); $this->assertFalse( $model['has_summary_metrics'] ); $this->assertEmpty( $model['result_rows'] ); }
	public function test_34_failed_reports_do_not_show_approved_strip() { $report = $this->template( 'single-coa-report.php' ); $this->assertStringContainsString( "\$test['show_qc_strip']", $report ); $this->assertStringNotContainsString( "'failed' === \$test['coa_status'] && \$test['is_full_qc_documented']", $report ); }
	public function test_35_mobile_cards_use_the_same_result_rows_as_table() { $template = $this->template( 'partials/full-qc-results-table.php' ); $this->assertSame( 2, substr_count( $template, "foreach ( \$test['result_rows'] as \$row )" ) ); $this->assertStringContainsString( 'ps-coa-results-cards', $template ); }
	public function test_36_required_section_headings_are_in_order() { $report = $this->template( 'single-coa-report.php' ); $needles = array( 'report-summary-metrics.php', 'full-qc-status-strip.php', 'full-qc-results-table.php', 'certificate-pages.php', 'batch-identity-gallery.php', 'laboratory-report-panel.php', 'report-navigation.php' ); $last = -1; foreach ( $needles as $needle ) { $position = strpos( $report, $needle ); $this->assertNotFalse( $position ); $this->assertGreaterThan( $last, $position ); $last = $position; } }
	public function test_37_major_sections_have_distinct_wrappers_and_spacing() { $report = $this->template( 'single-coa-report.php' ); $this->assertGreaterThanOrEqual( 3, substr_count( $report, 'ps-coa-report-panel' ) ); $css = str_replace( ' ', '', $this->css() ); $this->assertStringContainsString( '.ps-coa-report--mockup-layout.ps-coa-report-panel{margin-top:16px', $css ); $this->assertStringNotContainsString( 'margin-block:clamp(3rem,5vw,4rem)', $css ); }
	public function test_38_archive_and_history_routes_remain_intact() { $source = file_get_contents( dirname( __DIR__ ) . '/includes/class-rewrites.php' ); $this->assertStringContainsString( 'testing/?$', $source ); $this->assertStringContainsString( 'testing/([^/]+)/?$', $source ); }
	public function test_39_csv_importer_remains_intact() { $this->assertFileExists( dirname( __DIR__ ) . '/assets/js/coa-test-importer.js' ); $source = file_get_contents( dirname( __DIR__ ) . '/includes/class-coa-test-importer.php' ); $this->assertStringContainsString( 'fentanyl_status', $source ); $this->assertStringContainsString( 'fentanyl_notes', $source ); $this->assertStringNotContainsString( "'batch_vial_photo'", $source ); }
	public function test_40_design_and_copy_settings_remain_intact() { $fields = PepSelect\COAArchive\Design_Settings::fields(); $this->assertArrayHasKey( 'archive_title', $fields ); $this->assertArrayHasKey( 'report_hero_copy', $fields ); $this->assertArrayHasKey( 'document_bg', $fields ); }
	public function test_41_no_woocommerce_product_page_hooks_were_added() { $source = $this->all_php(); foreach ( array( 'woocommerce_before_single_product', 'woocommerce_single_product_summary', 'woocommerce_after_single_product' ) as $hook ) { $this->assertStringNotContainsString( $hook, $source ); } }
	public function test_42_no_qr_code_functionality_was_added() { $source = strtolower( $this->all_php() . $this->public_templates() ); $this->assertStringNotContainsString( 'qrcode', $source ); $this->assertStringNotContainsString( 'qr_code', $source ); }

	private function validate( $value, $name ) { return $this->validator->validate( true, $value, array( 'name' => $name ), '' ); }
	private function stage( $stage ) { return array( 'field_ps_coa_test_workflow_stage' => $stage, 'field_ps_coa_test_status' => 'pending' ); }
	private function attachment( $mime ) { return self::factory()->post->create( array( 'post_type' => 'attachment', 'post_status' => 'inherit', 'post_mime_type' => $mime, 'guid' => 'https://example.org/media/' . wp_generate_uuid4() ) ); }
	private function compound() { $id = self::factory()->post->create( array( 'post_type' => 'ps_compound', 'post_status' => 'publish', 'post_title' => 'Retatrutide' ) ); update_post_meta( $id, 'is_active', 1 ); return $id; }
	private function test_record( $compound ) { $id = self::factory()->post->create( array( 'post_type' => 'ps_coa_test', 'post_status' => 'publish', 'post_title' => 'Batch LEGACY' ) ); foreach ( array( 'compound_id' => $compound, 'workflow_stage' => 'complete', 'coa_status' => 'approved', 'batch_number' => 'LEGACY' ) as $key => $value ) { update_post_meta( $id, $key, $value ); } return $id; }
	private function fallback_fixture() { $compound = $this->compound(); $test = $this->test_record( $compound ); return array( 'compound' => $compound, 'test' => $test, 'batch' => $this->attachment( 'image/jpeg' ), 'featured' => $this->attachment( 'image/jpeg' ), 'compound_image' => $this->attachment( 'image/png' ) ); }
	private function summary( $ids ) { return $this->view->test_summary( get_post( $ids['test'] ), get_post( $ids['compound'] ) ); }
	private function fields() { return file_get_contents( dirname( __DIR__ ) . '/includes/class-coa-test-fields.php' ); }
	private function template( $path ) { return file_get_contents( dirname( __DIR__ ) . '/templates/' . $path ); }
	private function public_templates() { $source = ''; foreach ( glob( dirname( __DIR__ ) . '/templates/*.php' ) as $path ) { $source .= file_get_contents( $path ); } foreach ( glob( dirname( __DIR__ ) . '/templates/partials/*.php' ) as $path ) { $source .= file_get_contents( $path ); } return $source; }
	private function css() { return file_get_contents( dirname( __DIR__ ) . '/assets/css/pepselect-coa-frontend.css' ); }
	private function all_php() { $source = ''; foreach ( glob( dirname( __DIR__ ) . '/includes/*.php' ) as $path ) { $source .= file_get_contents( $path ); } return $source; }
}
