<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$ps_context = isset( $ps_context ) ? $ps_context : get_query_var( 'ps_coa_context', array() );
$ps_embedded = isset( $ps_embedded ) && $ps_embedded;
$compound = $ps_context['compound']; $test = $ps_context['test'];
if ( ! $ps_embedded ) { get_header(); }
?>
<main class="ps-coa ps-coa-app ps-coa-report" id="ps-coa-main">
	<nav class="ps-coa-breadcrumb" aria-label="<?php esc_attr_e( 'Breadcrumb', 'pepselect-coa-archive' ); ?>"><ol><li><a href="<?php echo esc_url( $ps_context['archive_url'] ); ?>"><?php esc_html_e( 'Testing & Documentation', 'pepselect-coa-archive' ); ?></a></li><li><a href="<?php echo esc_url( $compound['url'] ); ?>"><?php echo esc_html( $compound['display_name'] ); ?></a></li><li aria-current="page"><?php echo esc_html( $test['batch_number'] ); ?></li></ol></nav>
	<header class="ps-coa-report-header">
		<div><p class="ps-coa-eyebrow"><?php esc_html_e( 'Certificate of Analysis', 'pepselect-coa-archive' ); ?></p><h1><?php echo esc_html( $compound['public_name'] ); ?></h1><?php if ( $compound['strength_value_display'] && $compound['display_strength_separately'] ) : ?><p class="ps-coa-strength"><span><?php echo esc_html( trim( $compound['strength_value_display'] . ' ' . $compound['strength_unit'] ) ); ?></span></p><?php endif; ?><p class="ps-coa-report-header__batch"><?php echo esc_html( sprintf( __( 'Batch %s', 'pepselect-coa-archive' ), $test['batch_number'] ) ); ?></p></div>
		<dl><div><dt><?php esc_html_e( 'Status', 'pepselect-coa-archive' ); ?></dt><dd><?php $status = $test['coa_status_data']; include pepselect_coa_template_path( 'partials/status-indicator.php' ); ?></dd></div><div><dt><?php esc_html_e( 'Tested', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['test_date_label'] ?: __( 'Not available', 'pepselect-coa-archive' ) ); ?></dd></div><div><dt><?php esc_html_e( 'Laboratory', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['laboratory'] ?: __( 'Not available', 'pepselect-coa-archive' ) ); ?></dd></div></dl>
	</header>
	<div class="ps-coa-report-state ps-coa-report-state--<?php echo esc_attr( $test['public_status_tone'] ); ?>"><strong><?php echo esc_html( $test['public_status_label'] ); ?></strong><span><?php echo esc_html( $test['public_status_copy'] ); ?></span></div>
	<?php include pepselect_coa_template_path( 'partials/batch-identity.php' ); ?>
	<?php if ( in_array( $test['coa_status'], array( 'approved', 'failed' ), true ) ) : ?><section class="ps-coa-section" aria-labelledby="ps-summary-metrics"><div class="ps-coa-section-heading"><p class="ps-coa-eyebrow"><?php esc_html_e( 'Measured values', 'pepselect-coa-archive' ); ?></p><h2 id="ps-summary-metrics"><?php esc_html_e( 'Summary Metrics', 'pepselect-coa-archive' ); ?></h2></div><?php include pepselect_coa_template_path( 'partials/report-metrics.php' ); ?></section>
	<section class="ps-coa-section" aria-labelledby="ps-qc-results"><div class="ps-coa-section-heading"><p class="ps-coa-eyebrow"><?php esc_html_e( 'Independent laboratory data', 'pepselect-coa-archive' ); ?></p><h2 id="ps-qc-results"><?php esc_html_e( 'Full-QC Results', 'pepselect-coa-archive' ); ?></h2></div><?php include pepselect_coa_template_path( 'partials/report-results.php' ); ?></section><?php endif; ?>
	<?php include pepselect_coa_template_path( 'partials/report-documentation.php' ); ?>
	<?php if ( $test['page_images'] ) { include pepselect_coa_template_path( 'partials/certificate-gallery.php' ); } ?>
	<?php if ( $test['public_notes'] || $test['report_notes'] ) : ?><section class="ps-coa-section ps-coa-notes" aria-labelledby="ps-report-notes"><div class="ps-coa-section-heading"><h2 id="ps-report-notes"><?php esc_html_e( 'Report Notes', 'pepselect-coa-archive' ); ?></h2></div><?php if ( $test['public_notes'] ) : ?><div class="ps-coa-prose"><?php echo wp_kses_post( wpautop( $test['public_notes'] ) ); ?></div><?php endif; ?><?php if ( $test['report_notes'] ) : ?><div class="ps-coa-prose"><?php echo wp_kses_post( wpautop( $test['report_notes'] ) ); ?></div><?php endif; ?></section><?php endif; ?>
	<nav class="ps-coa-report-nav" aria-label="<?php esc_attr_e( 'Report navigation', 'pepselect-coa-archive' ); ?>"><div><a class="ps-coa-text-link" href="<?php echo esc_url( $compound['url'] ); ?>"><?php esc_html_e( 'Back to testing history', 'pepselect-coa-archive' ); ?></a><a class="ps-coa-text-link" href="<?php echo esc_url( $ps_context['archive_url'] ); ?>"><?php esc_html_e( 'Back to testing archive', 'pepselect-coa-archive' ); ?></a></div><div><?php if ( $ps_context['previous_report'] ) : ?><a class="ps-coa-button ps-coa-button--secondary" href="<?php echo esc_url( $ps_context['previous_report']['detail_url'] ); ?>"><?php echo esc_html( sprintf( __( 'Previous: batch %s', 'pepselect-coa-archive' ), $ps_context['previous_report']['batch_number'] ) ); ?></a><?php endif; ?><?php if ( $ps_context['next_report'] ) : ?><a class="ps-coa-button ps-coa-button--secondary" href="<?php echo esc_url( $ps_context['next_report']['detail_url'] ); ?>"><?php echo esc_html( sprintf( __( 'Next: batch %s', 'pepselect-coa-archive' ), $ps_context['next_report']['batch_number'] ) ); ?></a><?php endif; ?></div></nav>
</main>
<?php if ( ! $ps_embedded ) { get_footer(); } ?>
