<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$ps_context = isset( $ps_context ) ? $ps_context : get_query_var( 'ps_coa_context', array() );
$ps_embedded = isset( $ps_embedded ) && $ps_embedded; $compound = $ps_context['compound']; $test = $ps_context['test'];
if ( ! $ps_embedded ) { get_header(); }
?>
<main class="ps-coa ps-coa-report" id="ps-coa-main">
	<nav class="ps-coa__breadcrumb" aria-label="<?php esc_attr_e( 'Breadcrumb', 'pepselect-coa-archive' ); ?>"><a href="<?php echo esc_url( $ps_context['archive_url'] ); ?>"><?php esc_html_e( 'Testing & Documentation', 'pepselect-coa-archive' ); ?></a> <span aria-hidden="true">/</span> <a href="<?php echo esc_url( $compound['url'] ); ?>"><?php echo esc_html( $compound['display_name'] ); ?></a> <span aria-hidden="true">/</span> <span aria-current="page"><?php echo esc_html( $test['batch_number'] ); ?></span></nav>
	<header class="ps-coa__header">
		<h1><?php echo esc_html( $compound['display_name'] ); ?></h1>
		<p><?php echo esc_html( sprintf( __( 'Batch %s', 'pepselect-coa-archive' ), $test['batch_number'] ) ); ?></p>
		<dl class="ps-coa__facts"><dt><?php esc_html_e( 'Test date', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['test_date_label'] ?: __( 'Not available', 'pepselect-coa-archive' ) ); ?></dd><dt><?php esc_html_e( 'Status', 'pepselect-coa-archive' ); ?></dt><dd><span class="ps-coa__status <?php echo esc_attr( $test['coa_status_data']['class'] ); ?>"><?php echo esc_html( $test['coa_status_data']['label'] ); ?></span></dd><dt><?php esc_html_e( 'Laboratory', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( $test['laboratory'] ); ?></dd></dl>
	</header>
	<section aria-labelledby="ps-primary-results"><h2 id="ps-primary-results"><?php esc_html_e( 'Primary Results', 'pepselect-coa-archive' ); ?></h2>
		<dl class="ps-coa__facts ps-coa__facts--results">
			<dt><?php esc_html_e( 'Purity', 'pepselect-coa-archive' ); ?></dt><dd><?php echo '' !== $test['purity_percentage'] ? esc_html( $test['purity_percentage'] . '%' ) : esc_html__( 'Not reported', 'pepselect-coa-archive' ); ?><?php if ( $test['purity_method'] ) { echo ' <span>(' . esc_html( $test['purity_method'] ) . ')</span>'; } ?></dd>
			<dt><?php esc_html_e( 'Net content', 'pepselect-coa-archive' ); ?></dt><dd><?php echo esc_html( trim( $test['average_net_content'] . ' ' . $test['content_unit'] ) ?: __( 'Not reported', 'pepselect-coa-archive' ) ); ?></dd>
			<?php foreach ( array( 'identity_status' => __( 'Identity', 'pepselect-coa-archive' ), 'endotoxin_status' => __( 'Endotoxin', 'pepselect-coa-archive' ), 'heavy_metals_status' => __( 'Heavy metals', 'pepselect-coa-archive' ), 'sterility_status' => __( 'Sterility', 'pepselect-coa-archive' ) ) as $key => $label ) : ?><dt><?php echo esc_html( $label ); ?></dt><dd><?php $status = $test[ $key ]; include pepselect_coa_template_path( 'partials/report-status.php' ); ?></dd><?php endforeach; ?>
		</dl>
		<?php if ( $test['endotoxin_result'] || $test['heavy_metals_summary'] || $test['sterility_result'] ) : ?><div class="ps-coa__details"><?php if ( $test['endotoxin_result'] ) : ?><p><strong><?php esc_html_e( 'Endotoxin result:', 'pepselect-coa-archive' ); ?></strong> <?php echo esc_html( trim( $test['endotoxin_result'] . ' ' . $test['endotoxin_unit'] ) ); ?></p><?php endif; ?><?php if ( $test['heavy_metals_summary'] ) : ?><p><strong><?php esc_html_e( 'Heavy metals summary:', 'pepselect-coa-archive' ); ?></strong> <?php echo esc_html( $test['heavy_metals_summary'] ); ?></p><?php endif; ?><?php if ( $test['sterility_result'] ) : ?><p><strong><?php esc_html_e( 'Sterility result:', 'pepselect-coa-archive' ); ?></strong> <?php echo esc_html( $test['sterility_result'] ); ?></p><?php endif; ?></div><?php endif; ?>
	</section>
	<section aria-labelledby="ps-documentation"><h2 id="ps-documentation"><?php esc_html_e( 'Documentation', 'pepselect-coa-archive' ); ?></h2><p class="ps-coa__actions">
		<?php if ( $test['lab_report_url'] ) : ?><a class="ps-coa__action ps-coa__action--primary" href="<?php echo esc_url( $test['lab_report_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'View Lab Report', 'pepselect-coa-archive' ); ?></a><?php elseif ( $test['lab_verification_url'] ) : ?><a class="ps-coa__action" href="<?php echo esc_url( $test['lab_verification_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Verify with Laboratory', 'pepselect-coa-archive' ); ?></a><?php endif; ?>
		<?php if ( $test['pdf_url'] ) : ?><a class="ps-coa__action" href="<?php echo esc_url( $test['pdf_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Download Original PDF', 'pepselect-coa-archive' ); ?></a><?php endif; ?>
	</p><?php if ( $test['verification_code'] ) : ?><p><strong><?php esc_html_e( 'Access Code:', 'pepselect-coa-archive' ); ?></strong> <?php echo esc_html( $test['verification_code'] ); ?></p><?php endif; ?><?php if ( $test['lab_report_url'] && $test['lab_verification_url'] ) : ?><p><a href="<?php echo esc_url( $test['lab_verification_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Lab Verification', 'pepselect-coa-archive' ); ?></a></p><?php endif; ?><?php if ( $test['public_notes'] ) : ?><div><?php echo wp_kses_post( wpautop( $test['public_notes'] ) ); ?></div><?php endif; ?><?php if ( $test['report_notes'] ) : ?><div><?php echo wp_kses_post( wpautop( $test['report_notes'] ) ); ?></div><?php endif; ?></section>
	<?php if ( $test['page_images'] ) : ?><section aria-labelledby="ps-certificate-pages"><h2 id="ps-certificate-pages"><?php esc_html_e( 'Certificate Pages', 'pepselect-coa-archive' ); ?></h2><ol class="ps-coa__gallery"><?php foreach ( $test['page_images'] as $image ) : ?><li><img src="<?php echo esc_url( $image['url'] ); ?>" alt="<?php echo esc_attr( $image['alt'] ); ?>" loading="lazy"></li><?php endforeach; ?></ol></section><?php endif; ?>
	<nav class="ps-coa__report-nav" aria-label="<?php esc_attr_e( 'Report navigation', 'pepselect-coa-archive' ); ?>"><a href="<?php echo esc_url( $compound['url'] ); ?>"><?php esc_html_e( 'Back to compound history', 'pepselect-coa-archive' ); ?></a><a href="<?php echo esc_url( $ps_context['archive_url'] ); ?>"><?php esc_html_e( 'Back to testing archive', 'pepselect-coa-archive' ); ?></a><?php if ( $ps_context['previous_report'] ) : ?><a href="<?php echo esc_url( $ps_context['previous_report']['detail_url'] ); ?>"><?php esc_html_e( 'Previous approved report', 'pepselect-coa-archive' ); ?></a><?php endif; ?><?php if ( $ps_context['next_report'] ) : ?><a href="<?php echo esc_url( $ps_context['next_report']['detail_url'] ); ?>"><?php esc_html_e( 'Next approved report', 'pepselect-coa-archive' ); ?></a><?php endif; ?></nav>
</main>
<?php if ( ! $ps_embedded ) { get_footer(); } ?>
